baseURL = 'https://www.alexislebel.fr/'
languageCode = 'fr-fr'
title = 'Alestrio'
theme="blist2"
DefaultContentLanguage = "fr"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Alexis LEBEL"
      introSubtitle = "Systems Engineer, but mostly a tinkerer"
      introPhoto = "/images/pp.webp"
    [[languages.en.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1
    [[languages.en.menu.main]]
        name = "About"
        url = "page/about/"
        weight = 2
    [[languages.en.menu.main]]
        name = "Top Post"
        url = "/en/blog/static_personnal_site/"
        weight = 4
  [languages.fr]
    contentDir = "content/fr" 
    weight = 2
    languageName = "Français"
    title = "Alestrio"
    [languages.fr.params]
      description = "Think, Tinker, Watch it working !"
      introTitle = "Alexis LEBEL"
      introSubtitle = "Ingénieur Systèmes dans l'industrie, mais surtout bidouilleur !"
      introPhoto = "/images/pp.jpg"
    [[languages.fr.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1
    [[languages.fr.menu.main]]
        name = "A propos de moi"
        url = "page/about/"
        weight = 2
    [[languages.fr.menu.main]]
        name = "Mentions légales"
        url = "page/legal"
        weight = 4
[params]
  darkModeToggle = true
  enableSearch = false
  enableEmoji = true
  copyright = "Copyright © 2026 - Alexis LEBEL · All rights reserved"
  favicon = "/favicon.svg"
  ascentColor = "bg-blue-200"
  frontBundle = "blog"
[params.homepage.social]
  title = "Follow me"
  description = "Scientist, Engineer, Tinkerer, Homelabber"
  twitter = "https://twitter.com/Alestrio0"
  linkedin = "https://www.linkedin.com/in/alexis-lebel/"
  github = "https://github.com/Alestrio"
[[menu.main]]
  name = "About"
  url = "/about"
[build]
  writeStats = true
[outputs]
  home = ["HTML", "RSS", "JSON"]
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    unsafe = true
