name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.129.0'
          extended: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm ci || npm install
          fi
          npm install postcss postcss-cli postcss-import autoprefixer

      - name: Build and Deploy
        run: |
          # Build Hugo
          hugo --gc --minify
          
          # Vérifier que public existe
          if [ ! -d "public" ]; then
            echo "Erreur: Dossier public non trouvé après build Hugo"
            exit 1
          fi
          
          echo "=== Contenu généré par Hugo ==="
          ls -la public/
          
          # Configuration git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Aller dans le dossier public
          cd public
          
          # Initialiser git dans public
          git init
          git add .
          git commit -m "Deploy from ${{ github.sha }}"
          
          # Push vers gh-pages en écrasant
          git push --force "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:gh-pages
          
          echo "✅ Site déployé vers gh-pages"